/**
 * Created by leibo on 18/7/4.
 */
export default {
  hotelPicList: state => state.hotelPicList,
  hotelIntroduceList: state => state.hotelIntroduceList,
  hotelThemeTypeList: state => state.hotelThemeTypeList,
  hotelList: state => state.hotelList,
  hotelDetails: state => state.hotelDetails,
  hotelSearchRoomInfoList: state => state.hotelSearchRoomInfoList,
  hotelRoomHardList: state => state.hotelRoomHardList,
  hotelQueryObj: state => state.hotelQueryObj,
  hotelShowImg: state => state.hotelShowImg,
  hotelShowImgList: state => state.hotelShowImgList,
  hotelOrderInfo: state => state.hotelOrderInfo,
  roomInfo: state => state.roomInfo,
  hotelSearchObjD: state => state.hotelSearchObjD,
  HardService: state => state.HardService,
  HardServiceHard: state => state.HardServiceHard,
  HotelIco: state => state.HotelIco,
  HotelImage: state => state.HotelImage,
  HotelIntroduce: state => state.HotelIntroduce,
  HotelMinPrice: state => state.HotelMinPrice,
  HotelModel: state => state.HotelModel,
  HotelPolicy: state => state.HotelPolicy,
  HotelTheme: state => state.HotelTheme,
  seasonPlay: state => state.seasonPlay,
  featureRecommend: state => state.featureRecommend,
  chainHotel: state => state.chainHotel,
  RoomHard: state => state.RoomHard,
  ThemeType: state => state.ThemeType,
  BedType: state => state.BedType,
  BreakfastType: state => state.BreakfastType,
  CancelType: state => state.CancelType,
  WafiType: state => state.WafiType,
  hotelRoomNumList: state => state.hotelRoomNumList,
  hotelRoomOneList: state => state.hotelRoomOneList,
  hotelRoomOneRoomList: state => state.hotelRoomOneRoomList,
  hotelOrderInfoObj: state => state.hotelOrderInfoObj,
  hotelSelectRoomList: state => state.hotelSelectRoomList,
  hotelScrollTop: state => state.hotelScrollTop,
}
